inherit_from: .rubocop_todo.yml

require:
  - rubocop-flexport
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 512

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleMemoizedHelpers:
  Max: 20

Style/Documentation:
  Exclude:
    - db/migrate/*
    - test/**/*

Style/OpenStructUse:
  Exclude:
    - spec/**/*
    - test/**/*
