// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"

// Legacy
import "bootstrap"
import "chart"
import "chartjs-plugin-datalabels"
import "legacy/data_table"
import "legacy/bootstrap"
import "legacy/money_format"
import "legacy/date_format"
import "legacy/twitter"
import "legacy/eventsource"
import "legacy/service-runner"
import "legacy/stock_refresh"
import "legacy/data_refresh"
import "legacy/datatables"
import "legacy/data_unpack"
import "legacy/representation"
import "legacy/jcountdown"
import "legacy/local-store"
import "legacy/checkbox-menu"
import "https://s3.tradingview.com/tv.js"
